### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by tyiannak** [theopsall/video_annotator#3]
I'm getting the following internal server error:

```
[2020-11-01 21:01:05,845] ERROR in app: Exception on /finish [POST]
Traceback (most recent call last):
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tyiannak/Research/libraries/video_annotator/video_annotator/routes.py", line 56, in finish
    return render_template("profile.html", title='Home VAT', message=message)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/tyiannak/Research/libraries/video_annotator/video_annotator/templates/profile.html", line 1, in top-level template code
    {% extends "layouts.html" %}
  File "/Users/tyiannak/Research/libraries/video_annotator/video_annotator/templates/layouts.html", line 19, in top-level template code
    {% block heading %} {% endblock %}
  File "/Users/tyiannak/Research/libraries/video_annotator/video_annotator/templates/profile.html", line 8, in block "heading"
    {% if num_videos > already_annotated %}
jinja2.exceptions.UndefinedError: 'num_videos' is undefined
```

**Comment by theopsall** [comment]
@tyiannak  I think it is fixed now. Please take a look to be sure

**Comment by tyiannak** [comment]
thanx @theopsall works now
